# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'CountriesExplorerTask' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

      pod 'Alamofire', '5.10.2'
      pod 'Firebase/Crashlytics', '12.4.0'
      pod 'SwiftLint', '0.62.1'
      pod 'NeedleFoundation', '0.25.1'
      pod 'AlertToast', '1.3.9'

  target 'CountriesExplorerTaskTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CountriesExplorerTaskUITests' do
    # Pods for testing
  end

end
